### ISSUE TITLE
Graphical errors when using dynamic wallpapers

### ISSUE THREAD

**Issue by shiruken** [shiruken/hackintosh#3]
Setting the desktop background to a dynamic wallpaper results in a graphical glitch that extends across much of the screen. This occurs regardless of selecting the "dynamic" or "still" options for the wallpaper. There is no apparent solution other than selecting a standard desktop image. The issue appears to be related to the AMD Radeon 5700 XT graphics card.

![Screen Shot 2019-12-07 at 9 51 05 PM](https://user-images.githubusercontent.com/867617/70383923-e42ada80-193b-11ea-9cd6-97b955949f91.png)

**Comment by shiruken** [comment]
Reddit user documenting the same issue: https://www.reddit.com/r/hackintosh/comments/dw0e9m/catalina_dynamic_wallpaper_issue/

**Comment by Galeas** [comment]
It was fixed with 10.15.2

**Comment by shiruken** [comment]
> It was fixed with 10.15.2

Unfortunately I just updated to 10.15.2 and it's still happening.

**Comment by Galeas** [comment]
> Unfortunately I just updated to 10.15.2 and it's still happening.

Did you tried another screen resolution? I've read somewhere that this bug could be related to 2k resolution.

**Comment by shiruken** [comment]
Just tried with a 1080p monitor and there's not issue. So it certainly seems related to the 1440p display size.

**Comment by shiruken** [comment]
Partially resolved by macOS 10.15.3 (42699d3be7c36fa592b8e51a176504aef72f6369). The "Dynamic" desktop image option now work properly for 1440p displays. The "Still" mode still results in the graphical error.

![DynamicWallpaperWorking](https://user-images.githubusercontent.com/867617/73597896-d7b79e00-44f6-11ea-859e-70e2e9f48604.png)
![StillWallpaperBroken](https://user-images.githubusercontent.com/867617/73597897-d8e8cb00-44f6-11ea-9cf5-65fbf5114368.png)
